print (""+col)
print ("              __  __ _______      __ "+co)
print ("             |  \/  |  __ \ \    / / "+co)
print ("             | \  / | |__) \ \  / / "+l)
print ("             | |\/| |  _  / \ \/ / "+h)
print ("             | |  | | | \ \  \  / "+col)
print ("             |_|  |_|_|  \_\  \/ \n\n\n "+c)
print ("        ______________________________")
print ("              My Chanel : Qais Alhamwi")
print ("        ______________________________")
print ("             My Insta : asta al0hmawi")
print ("        ______________________________")
print ("                Groub : Qais \n\n\n\n\n")

sender = input(" Enter your Email : ")
password = input("Enter the Password : ")
receiver = input("Enter your Receiver : ")
message =input ("Enter your Message : ")
try:
        server = smtplib.SMTP_SSL('smtp.gmail.com', 465)
        server.login(sender,password)
        server.sendmail( sender ,receiver,  message)
        server.quit()
        print(' sent Successfully')
except:
        print(' there is error ')
